name: Generate Snake Animation 🐍

on:
  schedule:
    - cron: "0 */12 * * *"  # dijalankan tiap 12 jam
  workflow_dispatch:       # bisa dijalankan manual juga

jobs:
  build:
    name: Generate GitHub Contribution Snake
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate snake SVG
        uses: Platane/snk@master
        with:
          github_user_name: FaizalSetiawan
          outputs: dist/snake.svg

      - name: Upload snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
